### PR TITLE
submit event isnt fired on submitting via javascript

### PR DESCRIPTION
**Pull request by schelmo**
call formEvent() when calling submit() since the submit event doesnt fire and loading stays false

### CODE REVIEW

**Comment by arian** [comment]
so the `this.form.submit()` doesn't fire the form submit event?

**Comment by schelmo** [comment]
jeah
http://jsfiddle.net/d2w9t/

**Comment by arian** [comment]
right, I don't think we need the `if` though.. could you change that, and then i'll pull.

**Comment by arian** [comment]
awesome thanks!

**Pull request merged**
